export type Nakshatra = {
  number: number;
  name: string;
  nameHi: string;
  symbol: string;
  deity: string;
  deityHi: string;
  lord: string;
  lordHi: string;
  rashiSpan: string;
  gana: "Deva" | "Manushya" | "Rakshasa";
  yoni: string;
  varna: "Brahmin" | "Kshatriya" | "Vaishya" | "Shudra";
  nature: string;
};

export const NAKSHATRAS: Nakshatra[] = [
  {
    number: 1,
    name: "Ashwini",
    nameHi: "अश्विनी",
    symbol: "Horse's head",
    deity: "Ashwini Kumaras",
    deityHi: "अश्विनी कुमार",
    lord: "Ketu",
    lordHi: "केतु",
    rashiSpan: "Mesha 0°00′ – 13°20′",
    gana: "Deva",
    yoni: "Horse",
    varna: "Vaishya",
    nature: "Swift, healing, beginnings",
  },
  {
    number: 2,
    name: "Bharani",
    nameHi: "भरणी",
    symbol: "Yoni / female reproductive organ",
    deity: "Yama",
    deityHi: "यम",
    lord: "Shukra (Venus)",
    lordHi: "शुक्र",
    rashiSpan: "Mesha 13°20′ – 26°40′",
    gana: "Manushya",
    yoni: "Elephant",
    varna: "Kshatriya",
    nature: "Bearing, transformation, restraint",
  },
  {
    number: 3,
    name: "Krittika",
    nameHi: "कृत्तिका",
    symbol: "Razor / flame",
    deity: "Agni",
    deityHi: "अग्नि",
    lord: "Surya (Sun)",
    lordHi: "सूर्य",
    rashiSpan: "Mesha 26°40′ – Vrishabha 10°00′",
    gana: "Rakshasa",
    yoni: "Sheep",
    varna: "Brahmin",
    nature: "Sharp, purifying, critical",
  },
  {
    number: 4,
    name: "Rohini",
    nameHi: "रोहिणी",
    symbol: "Cart / chariot",
    deity: "Brahma / Prajapati",
    deityHi: "ब्रह्मा / प्रजापति",
    lord: "Chandra (Moon)",
    lordHi: "चन्द्र",
    rashiSpan: "Vrishabha 10°00′ – 23°20′",
    gana: "Manushya",
    yoni: "Serpent",
    varna: "Shudra",
    nature: "Growth, fertility, beauty",
  },
  {
    number: 5,
    name: "Mrigashira",
    nameHi: "मृगशिरा",
    symbol: "Deer's head",
    deity: "Soma / Chandra",
    deityHi: "सोम / चन्द्र",
    lord: "Mangala (Mars)",
    lordHi: "मंगल",
    rashiSpan: "Vrishabha 23°20′ – Mithuna 6°40′",
    gana: "Deva",
    yoni: "Serpent",
    varna: "Shudra",
    nature: "Searching, gentle, exploratory",
  },
  {
    number: 6,
    name: "Ardra",
    nameHi: "आर्द्रा",
    symbol: "Teardrop / gem",
    deity: "Rudra",
    deityHi: "रुद्र",
    lord: "Rahu",
    lordHi: "राहु",
    rashiSpan: "Mithuna 6°40′ – 20°00′",
    gana: "Manushya",
    yoni: "Dog",
    varna: "Brahmin",
    nature: "Storm, transformation through tears",
  },
  {
    number: 7,
    name: "Punarvasu",
    nameHi: "पुनर्वसु",
    symbol: "Quiver of arrows",
    deity: "Aditi",
    deityHi: "अदिति",
    lord: "Guru (Jupiter)",
    lordHi: "गुरु",
    rashiSpan: "Mithuna 20°00′ – Karka 3°20′",
    gana: "Deva",
    yoni: "Cat",
    varna: "Vaishya",
    nature: "Renewal, return, abundance",
  },
  {
    number: 8,
    name: "Pushya",
    nameHi: "पुष्य",
    symbol: "Cow's udder / lotus",
    deity: "Brihaspati",
    deityHi: "बृहस्पति",
    lord: "Shani (Saturn)",
    lordHi: "शनि",
    rashiSpan: "Karka 3°20′ – 16°40′",
    gana: "Deva",
    yoni: "Sheep",
    varna: "Kshatriya",
    nature: "Nourishment, prosperity, most auspicious",
  },
  {
    number: 9,
    name: "Ashlesha",
    nameHi: "आश्लेषा",
    symbol: "Coiled serpent",
    deity: "Nagas",
    deityHi: "नाग",
    lord: "Budha (Mercury)",
    lordHi: "बुध",
    rashiSpan: "Karka 16°40′ – 30°00′",
    gana: "Rakshasa",
    yoni: "Cat",
    varna: "Brahmin",
    nature: "Embrace, hidden, hypnotic",
  },
  {
    number: 10,
    name: "Magha",
    nameHi: "मघा",
    symbol: "Royal throne",
    deity: "Pitris (ancestors)",
    deityHi: "पितृ",
    lord: "Ketu",
    lordHi: "केतु",
    rashiSpan: "Simha 0°00′ – 13°20′",
    gana: "Rakshasa",
    yoni: "Rat",
    varna: "Shudra",
    nature: "Lineage, authority, ancestry",
  },
  {
    number: 11,
    name: "Purva Phalguni",
    nameHi: "पूर्व फाल्गुनी",
    symbol: "Front of a bed / hammock",
    deity: "Bhaga (Aryaman)",
    deityHi: "भग",
    lord: "Shukra (Venus)",
    lordHi: "शुक्र",
    rashiSpan: "Simha 13°20′ – 26°40′",
    gana: "Manushya",
    yoni: "Rat",
    varna: "Brahmin",
    nature: "Pleasure, romance, repose",
  },
  {
    number: 12,
    name: "Uttara Phalguni",
    nameHi: "उत्तर फाल्गुनी",
    symbol: "Back of a bed",
    deity: "Aryaman",
    deityHi: "अर्यमा",
    lord: "Surya (Sun)",
    lordHi: "सूर्य",
    rashiSpan: "Simha 26°40′ – Kanya 10°00′",
    gana: "Manushya",
    yoni: "Cow",
    varna: "Kshatriya",
    nature: "Patronage, generosity, marriage",
  },
  {
    number: 13,
    name: "Hasta",
    nameHi: "हस्त",
    symbol: "Hand / fist",
    deity: "Savitr (solar aspect)",
    deityHi: "सवितृ",
    lord: "Chandra (Moon)",
    lordHi: "चन्द्र",
    rashiSpan: "Kanya 10°00′ – 23°20′",
    gana: "Deva",
    yoni: "Buffalo",
    varna: "Vaishya",
    nature: "Skill, craftsmanship, dexterity",
  },
  {
    number: 14,
    name: "Chitra",
    nameHi: "चित्रा",
    symbol: "Bright jewel / pearl",
    deity: "Vishvakarma / Tvashtr",
    deityHi: "विश्वकर्मा / त्वष्टा",
    lord: "Mangala (Mars)",
    lordHi: "मंगल",
    rashiSpan: "Kanya 23°20′ – Tula 6°40′",
    gana: "Rakshasa",
    yoni: "Tiger",
    varna: "Shudra",
    nature: "Dazzling, aesthetic, illusion-piercing",
  },
  {
    number: 15,
    name: "Swati",
    nameHi: "स्वाति",
    symbol: "Young shoot in the wind",
    deity: "Vayu",
    deityHi: "वायु",
    lord: "Rahu",
    lordHi: "राहु",
    rashiSpan: "Tula 6°40′ – 20°00′",
    gana: "Deva",
    yoni: "Buffalo",
    varna: "Brahmin",
    nature: "Independence, scattering, breath",
  },
  {
    number: 16,
    name: "Vishakha",
    nameHi: "विशाखा",
    symbol: "Triumphal arch / forked branch",
    deity: "Indra-Agni",
    deityHi: "इन्द्र-अग्नि",
    lord: "Guru (Jupiter)",
    lordHi: "गुरु",
    rashiSpan: "Tula 20°00′ – Vrishchika 3°20′",
    gana: "Rakshasa",
    yoni: "Tiger",
    varna: "Kshatriya",
    nature: "Determined, goal-driven, achievement",
  },
  {
    number: 17,
    name: "Anuradha",
    nameHi: "अनुराधा",
    symbol: "Lotus / staff",
    deity: "Mitra",
    deityHi: "मित्र",
    lord: "Shani (Saturn)",
    lordHi: "शनि",
    rashiSpan: "Vrishchika 3°20′ – 16°40′",
    gana: "Deva",
    yoni: "Deer",
    varna: "Shudra",
    nature: "Friendship, devotion, organisation",
  },
  {
    number: 18,
    name: "Jyeshtha",
    nameHi: "ज्येष्ठा",
    symbol: "Earring / umbrella",
    deity: "Indra",
    deityHi: "इन्द्र",
    lord: "Budha (Mercury)",
    lordHi: "बुध",
    rashiSpan: "Vrishchika 16°40′ – 30°00′",
    gana: "Rakshasa",
    yoni: "Deer",
    varna: "Brahmin",
    nature: "Eldest, protective, guardianship",
  },
  {
    number: 19,
    name: "Mula",
    nameHi: "मूल",
    symbol: "Bunch of roots",
    deity: "Nirriti",
    deityHi: "निरृति",
    lord: "Ketu",
    lordHi: "केतु",
    rashiSpan: "Dhanu 0°00′ – 13°20′",
    gana: "Rakshasa",
    yoni: "Dog",
    varna: "Kshatriya",
    nature: "Root, dissolution, original cause",
  },
  {
    number: 20,
    name: "Purva Ashadha",
    nameHi: "पूर्वाषाढ़ा",
    symbol: "Elephant tusk / fan",
    deity: "Apas (waters)",
    deityHi: "आपः",
    lord: "Shukra (Venus)",
    lordHi: "शुक्र",
    rashiSpan: "Dhanu 13°20′ – 26°40′",
    gana: "Manushya",
    yoni: "Monkey",
    varna: "Brahmin",
    nature: "Invincibility, persuasion, philosophy",
  },
  {
    number: 21,
    name: "Uttara Ashadha",
    nameHi: "उत्तराषाढ़ा",
    symbol: "Elephant tusk / planks of a bed",
    deity: "Vishvedevas",
    deityHi: "विश्वेदेवाः",
    lord: "Surya (Sun)",
    lordHi: "सूर्य",
    rashiSpan: "Dhanu 26°40′ – Makara 10°00′",
    gana: "Manushya",
    yoni: "Mongoose",
    varna: "Kshatriya",
    nature: "Final victory, integrity, lasting achievement",
  },
  {
    number: 22,
    name: "Shravana",
    nameHi: "श्रवण",
    symbol: "Ear / three footprints",
    deity: "Vishnu",
    deityHi: "विष्णु",
    lord: "Chandra (Moon)",
    lordHi: "चन्द्र",
    rashiSpan: "Makara 10°00′ – 23°20′",
    gana: "Deva",
    yoni: "Monkey",
    varna: "Shudra",
    nature: "Listening, learning, connection",
  },
  {
    number: 23,
    name: "Dhanishta",
    nameHi: "धनिष्ठा",
    symbol: "Drum / flute",
    deity: "Vasus (eight)",
    deityHi: "अष्ट वसु",
    lord: "Mangala (Mars)",
    lordHi: "मंगल",
    rashiSpan: "Makara 23°20′ – Kumbha 6°40′",
    gana: "Rakshasa",
    yoni: "Lion",
    varna: "Vaishya",
    nature: "Wealth, rhythm, abundance through effort",
  },
  {
    number: 24,
    name: "Shatabhisha",
    nameHi: "शतभिषा",
    symbol: "Empty circle / 100 healers",
    deity: "Varuna",
    deityHi: "वरुण",
    lord: "Rahu",
    lordHi: "राहु",
    rashiSpan: "Kumbha 6°40′ – 20°00′",
    gana: "Rakshasa",
    yoni: "Horse",
    varna: "Shudra",
    nature: "Healing, secrecy, vastness",
  },
  {
    number: 25,
    name: "Purva Bhadrapada",
    nameHi: "पूर्व भाद्रपदा",
    symbol: "Front legs of a funeral cot",
    deity: "Aja Ekapada",
    deityHi: "अज एकपाद",
    lord: "Guru (Jupiter)",
    lordHi: "गुरु",
    rashiSpan: "Kumbha 20°00′ – Meena 3°20′",
    gana: "Manushya",
    yoni: "Lion",
    varna: "Brahmin",
    nature: "Intensity, transformation, fire",
  },
  {
    number: 26,
    name: "Uttara Bhadrapada",
    nameHi: "उत्तर भाद्रपदा",
    symbol: "Back legs of a funeral cot / serpent in waters",
    deity: "Ahirbudhnya",
    deityHi: "अहिर्बुध्न्य",
    lord: "Shani (Saturn)",
    lordHi: "शनि",
    rashiSpan: "Meena 3°20′ – 16°40′",
    gana: "Manushya",
    yoni: "Cow",
    varna: "Kshatriya",
    nature: "Depth, stability, oceanic wisdom",
  },
  {
    number: 27,
    name: "Revati",
    nameHi: "रेवती",
    symbol: "Fish / drum",
    deity: "Pushan",
    deityHi: "पूषन्",
    lord: "Budha (Mercury)",
    lordHi: "बुध",
    rashiSpan: "Meena 16°40′ – 30°00′",
    gana: "Deva",
    yoni: "Elephant",
    varna: "Shudra",
    nature: "Completion, journey, safe arrival",
  },
];
