export type Rashi = {
  number: number;
  name: string;
  nameHi: string;
  english: string;
  symbol: string;
  element: "Fire" | "Earth" | "Air" | "Water";
  quality: "Movable" | "Fixed" | "Dual";
  lord: string;
  lordHi: string;
  span: string;
  nakshatras: string;
};

export const RASHIS: Rashi[] = [
  {
    number: 1,
    name: "Mesha",
    nameHi: "मेष",
    english: "Aries",
    symbol: "Ram",
    element: "Fire",
    quality: "Movable",
    lord: "Mangala (Mars)",
    lordHi: "मंगल",
    span: "0° – 30°",
    nakshatras: "Ashwini, Bharani, Krittika (pada 1)",
  },
  {
    number: 2,
    name: "Vrishabha",
    nameHi: "वृषभ",
    english: "Taurus",
    symbol: "Bull",
    element: "Earth",
    quality: "Fixed",
    lord: "Shukra (Venus)",
    lordHi: "शुक्र",
    span: "30° – 60°",
    nakshatras: "Krittika (padas 2-4), Rohini, Mrigashira (padas 1-2)",
  },
  {
    number: 3,
    name: "Mithuna",
    nameHi: "मिथुन",
    english: "Gemini",
    symbol: "Couple",
    element: "Air",
    quality: "Dual",
    lord: "Budha (Mercury)",
    lordHi: "बुध",
    span: "60° – 90°",
    nakshatras: "Mrigashira (padas 3-4), Ardra, Punarvasu (padas 1-3)",
  },
  {
    number: 4,
    name: "Karka",
    nameHi: "कर्क",
    english: "Cancer",
    symbol: "Crab",
    element: "Water",
    quality: "Movable",
    lord: "Chandra (Moon)",
    lordHi: "चन्द्र",
    span: "90° – 120°",
    nakshatras: "Punarvasu (pada 4), Pushya, Ashlesha",
  },
  {
    number: 5,
    name: "Simha",
    nameHi: "सिंह",
    english: "Leo",
    symbol: "Lion",
    element: "Fire",
    quality: "Fixed",
    lord: "Surya (Sun)",
    lordHi: "सूर्य",
    span: "120° – 150°",
    nakshatras: "Magha, Purva Phalguni, Uttara Phalguni (pada 1)",
  },
  {
    number: 6,
    name: "Kanya",
    nameHi: "कन्या",
    english: "Virgo",
    symbol: "Virgin",
    element: "Earth",
    quality: "Dual",
    lord: "Budha (Mercury)",
    lordHi: "बुध",
    span: "150° – 180°",
    nakshatras: "Uttara Phalguni (padas 2-4), Hasta, Chitra (padas 1-2)",
  },
  {
    number: 7,
    name: "Tula",
    nameHi: "तुला",
    english: "Libra",
    symbol: "Scales",
    element: "Air",
    quality: "Movable",
    lord: "Shukra (Venus)",
    lordHi: "शुक्र",
    span: "180° – 210°",
    nakshatras: "Chitra (padas 3-4), Swati, Vishakha (padas 1-3)",
  },
  {
    number: 8,
    name: "Vrishchika",
    nameHi: "वृश्चिक",
    english: "Scorpio",
    symbol: "Scorpion",
    element: "Water",
    quality: "Fixed",
    lord: "Mangala (Mars)",
    lordHi: "मंगल",
    span: "210° – 240°",
    nakshatras: "Vishakha (pada 4), Anuradha, Jyeshtha",
  },
  {
    number: 9,
    name: "Dhanu",
    nameHi: "धनु",
    english: "Sagittarius",
    symbol: "Archer",
    element: "Fire",
    quality: "Dual",
    lord: "Guru (Jupiter)",
    lordHi: "गुरु",
    span: "240° – 270°",
    nakshatras: "Mula, Purva Ashadha, Uttara Ashadha (pada 1)",
  },
  {
    number: 10,
    name: "Makara",
    nameHi: "मकर",
    english: "Capricorn",
    symbol: "Sea-goat",
    element: "Earth",
    quality: "Movable",
    lord: "Shani (Saturn)",
    lordHi: "शनि",
    span: "270° – 300°",
    nakshatras: "Uttara Ashadha (padas 2-4), Shravana, Dhanishta (padas 1-2)",
  },
  {
    number: 11,
    name: "Kumbha",
    nameHi: "कुम्भ",
    english: "Aquarius",
    symbol: "Water-bearer",
    element: "Air",
    quality: "Fixed",
    lord: "Shani (Saturn)",
    lordHi: "शनि",
    span: "300° – 330°",
    nakshatras: "Dhanishta (padas 3-4), Shatabhisha, Purva Bhadrapada (padas 1-3)",
  },
  {
    number: 12,
    name: "Meena",
    nameHi: "मीन",
    english: "Pisces",
    symbol: "Fishes",
    element: "Water",
    quality: "Dual",
    lord: "Guru (Jupiter)",
    lordHi: "गुरु",
    span: "330° – 360°",
    nakshatras: "Purva Bhadrapada (pada 4), Uttara Bhadrapada, Revati",
  },
];
